apiVersion: apps/v1
kind: Deployment
metadata:
  name: frcnn-deploy
spec:
  selector:
    matchLabels:
      run: frcnn
  template:
    metadata:
      labels:
        run: frcnn
    spec:
      containers:
      - name: frcnn
        image: silverstar456/gdsc-project-test:frcnn
        ports: 
        - containerPort: 8080